/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as ClientIndexRouteImport } from './routes/client/indexclient'
import { Route as ClientClientIdRouteImport } from './routes/client.$clientId'

const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const ClientClientIdRoute = ClientClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/author': typeof AuthorRoute
  '/books': typeof BooksRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/author': typeof AuthorRoute
  '/client': typeof ClientRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/author': typeof AuthorRoute
  '/books': typeof BooksRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/author'
    | '/books'
    | '/client'
    | '/books/$bookId'
    | '/client/$clientId'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/author'
    | '/client'
    | '/books/$bookId'
    | '/client/$clientId'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/author'
    | '/books'
    | '/client'
    | '/books/$bookId'
    | '/client/clientId'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorRoute: typeof AuthorRoute
  BooksRoute: typeof BooksRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/client/$clientId': {
      id: '/client/$clientId'
      path: '/$clientId'
      fullPath: '/client/$clientId'
      preLoaderRoute: typeof ClientClientIdRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}
interface ClientRouteChildren {
  ClientIndexclientRoute: typeof ClientIndexRoute
  ClientClientIdRoute: typeof ClientClientIdRoute
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface ClientRouteChildren {
  ClientIndexclientRoute: typeof ClientIndexclientRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientIndexclientRoute,
  ClientClientIdRoute,
}

const ClientRouteWithChildren = ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorRoute: AuthorRoute,
  BooksRoute: BooksRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
